### ISSUE TITLE
ip6tables v1.8.4 (legacy): can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)

### ISSUE THREAD

**Issue by rubenanapu** [husarnet/docker-example#1]
Hi all.

I tried the docker example provided here, using the **docker-compose.yml** version but it never works for me.

Before this repository existed, I tried the instructions provided on https://docs.husarnet.com/docs/tutorial-docker/ to no avail.

I always have the problem mentioned in the title of this issue when I run `husarnet daemon`:

```
ip6tables v1.8.4 (legacy): can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.
ip6tables v1.8.4 (legacy): can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.
[3753489] setting iptables failed

```

Do you know how to solve this?

The **host** I'm using to run the dockers is:

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

Docker version 19.03.8, build afacb8b7f0
```

I'm using the same OS version as you and still doesn't work for me. Could it be that I have to install a specific package in the host?

I also tested in a Ubuntu 18.04 but it didn't work either. It failed for the same reason:
```
$lsb_release -a

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

$ docker --version
Docker version 19.03.12, build 48a66213fe

```

**Comment by rubenanapu** [comment]
Ok, the problem has been solved by adding the lines below to the Dockerfile provided in this repository:

```
RUN apt install iptables \
    && mv -v /usr/sbin/ip6tables /usr/sbin/ip6tables--DISABLED-$(date +"%Y-%m-%d--%H-%M") \
    && cp -v /usr/sbin/ip6tables-nft /usr/sbin/ip6tables
```

## How did I come to this point:

Miguel, from https://www.theconstructsim.com/ was talking to Dominik from Husarnet, and Dominik said the problem could be related to the iptables version.

I saw Dominik was using **iptables v1.8.5 (nf_tables)** while my iptables was **iptables v1.8.4 (legacy)**. 
The most important part in Dominik's version is "**nf_tables**".

Then after a lot of trials and errors, I found that in order to have **nf_tables** support, we need to use **ip6tables-nft** instead of **ip6tables**.

So what I did was just replace the original **ip6tables** with **ip6tables-nft**. Then the containers connected perfectly to Husarnet.

## My suggestions for Husarnet guys.

Modify Husarnet to use **ip6tables-nft** directly instead of **ip6tables**.

**Comment by zielmicha** [comment]
You should also be able to set ip6tables variant using (not tested):
`RUN update-alternatives --set ip6tables /usr/sbin/ip6tables-nft`
which might be a bit more robust (e.g. won't be overridden by other apt-get commands)

**Comment by rubenanapu** [comment]
Thanks, @zielmicha, 

I tested your solution and it worked fine :+1:
